name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.3

    - name: Execute Index Page with PHP Vanilla Script
      run: php ./index.php
